# pull official base image
FROM python:3.9.5

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install supervisord
RUN apt-get update && apt-get install -y supervisor

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt


# copy project
COPY . /usr/src/app/


# run supervisord
# CMD ["/usr/bin/supervisord"]

RUN mkdir -p /var/log/supervisor
COPY ./supervisor_app.conf /etc/supervisor/conf.d/supervisor_app.conf
COPY ./supervisord.conf /etc/supervisor/supervisord.conf
ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
