#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

/usr/local/bin/gunicorn --config python:core.gunicorn core.wsgi --timeout 800 --bind 0.0.0.0:8000 --workers 4 --limit-request-line 0 --access-logfile '-' --error-logfile '-'
