#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset
# cp -r /app/compose/node/public/static/src_node /app/pixl/static/
# cp -r /app/compose/node/public/static/static_node /app/pixl/static/
# python /app/manage.py collectstatic --noinput --clear
#python /app/manage.py makemigrations
#python /app/manage.py migrate
#daphne -b 0.0.0.0 -p 8000 config.routing:application
#/usr/local/bin/gunicorn config.wsgi --timeout 100  --bind 0.0.0.0:8000 --workers   --limit-request-line 0 --chdir=/app --access-logfile '-' --error-logfile '-' 
/usr/local/bin/gunicorn --config python:core.gunicorn core.wsgi --timeout 800 --bind 0.0.0.0:8000 --workers 4 --limit-request-line 0 --access-logfile '-' --error-logfile '-'
